### PR TITLE
Update Home_1.cpp

### PR DESCRIPTION
**Pull request by its-saurabh26**
Remove the Unnecessary Space in the code and Beautify the code.

### CODE REVIEW

**Comment by its-saurabh26** [comment]
Remove the unnecessary white space and correct the alignments.

**Comment by its-saurabh26** [comment]
Remove the unnecessary white space and correct the alignments.

**Comment by its-Saurabh23** [comment]
OK , I got the point Now In am  going to merge the update source  code file. 
Thanks for doing this .we will go further ahead  in future :)

**Review by its-Saurabh23 — COMMENTED** [review]
I change.

**Pull request closed without merging**
